# Site settings
title: 潮落空间
email: zhb6696@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 个人博客，读书-写作-工作
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://san.sanrabbit.com" # the base hostname & protocol for your site
#twitter_username: zhb6696
github_username:  zhb6696
Sina weibo: hongbo_brady

# Build settings
markdown: rdiscount

permalink: /:year/:month/:day/:title.html
